[build]
  publish = "public"  # נתיב לקבצים הסטטיים שלך
  functions = "netlify/functions"  # נתיב לפונקציות Serverless

[functions]
  node_bundler = "esbuild"  # בונה את הפונקציות בצורה אופטימלית

[build.environment]
  NODE_VERSION = "18"  # גרסת Node.js
